using System;

/// <summary>
/// Namespace containing hook modules for the AmeisenBotX.Wow.Hook library.
/// </summary>
namespace AmeisenBotX.Wow.Hook.Modules
{
    /// <summary>
    /// Represents an interface for a hook module that provides assembly instructions and data processing functions.
    /// </summary>
    public interface IHookModule
    {
        /// <summary>
        /// Pointer to the assembly instructions used by this module.
        /// </summary>
        IntPtr AsmAddress { get; }

        /// <summary>
        /// Gets polled when new data is available.
        /// </summary>
        Action<IntPtr> OnDataUpdate { get; set; }

        /// <summary>
        /// Gets polled every tick.
        /// </summary>
        Action<IHookModule> Tick { get; set; }

        /// <summary>
        /// Get the pointer to the output data generated by this module.
        /// </summary>
        /// <returns>Pointer to data inside the wow process, read it with read process memory.</returns>
        IntPtr GetDataPointer();

        /// <summary>
        /// Try to inject the module.
        /// </summary>
        /// <returns>True is injected, false if something went wrong</returns>
        bool Inject();
    }
}